route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'telegram-alert'
  routes:
  - match:
      severity: critical
    receiver: 'telegram-alert'
receivers:
  - name: 'telegram-alert'
    telegram_configs:
    - chat_id: 793490762
      bot_token: 7660732426:AAH2zZ9dNjFIZY8Q_ejlN5DTdZmeDS9nYCc
      send_resolved: true
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
