version: "3.8"

services:
  # Prometheus Service
  prometheus:
    build:
      context: ./prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring-network

  # Grafana Service
  grafana:
    build:
      context: ./grafana  # Pfad zu deinem Grafana Dockerfile
    image: grafana-custom
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Standardpasswort für Admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - monitoring-network

  # Node Exporter Service
  node-exporter:
    build:
      context: ./node_exporter
    container_name: node_exporter
    ports:
      - "9100:9100"
    networks:
      - monitoring-network

  # Alertmanager Service
  alertmanager:
    build:
      context: ./alertmanager
    container_name: alertmanager
    ports:
      - "9093:9093"
    networks:
      - monitoring-network
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml

  # Spring Boot App Service
  api:
    build:
      context: api  # Der Ordner, in dem sich das Dockerfile für die Spring Boot App befindet
    container_name: api
    ports:
      - "8080:8080"
    networks:
      - monitoring-network
    depends_on:
      - prometheus  # Abhängig von Prometheus

networks:
  monitoring-network:
    driver: bridge
