# Base image for Grafana
FROM grafana/grafana:11.3.1

# Set environment variables (optional)
ENV GF_SECURITY_ADMIN_PASSWORD=admin
ENV GF_SERVER_HTTP_PORT=3000

# Expose Grafana port
EXPOSE 3000

#CMD ["/bin/bash", "-c", "/bin/grafana-server web"]
